insert into players (name, email, password, role) values ('James Anderson', 'james.anderson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Michael Chen', 'michael.chen@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('David Johnson', 'david.johnson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Jennifer Smith', 'jennifer.smith@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Sarah Williams', 'sarah.williams@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Robert Brown', 'robert.brown@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Emily Davis', 'emily.davis@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Christopher Wilson', 'christopher.wilson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Amanda Martinez', 'amanda.martinez@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Daniel Rodriguez', 'daniel.rodriguez@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Jessica Taylor', 'jessica.taylor@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Matthew Thomas', 'matthew.thomas@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Ashley Jackson', 'ashley.jackson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Joshua White', 'joshua.white@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Megan Harris', 'megan.harris@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Kevin Martin', 'kevin.martin@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Rachel Thompson', 'rachel.thompson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Brian Moore', 'brian.moore@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Lauren Clark', 'lauren.clark@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Edward Lewis', 'edward.lewis@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Nicole Lee', 'nicole.lee@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Ryan Walker', 'ryan.walker@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Hannah Scott', 'hannah.scott@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Jason Green', 'jason.green@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Brittany Adams', 'brittany.adams@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Gary Nelson', 'gary.nelson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Kayla Carter', 'kayla.carter@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Steven Mitchell', 'steven.mitchell@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Abigail Perez', 'abigail.perez@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Paul Roberts', 'paul.roberts@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Alexis Phillips', 'alexis.phillips@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Mark Campbell', 'mark.campbell@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Sophia Parker', 'sophia.parker@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Donald Evans', 'donald.evans@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Olivia Edwards', 'olivia.edwards@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('George Collins', 'george.collins@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Isabella Reeves', 'isabella.reeves@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Kenneth Morris', 'kenneth.morris@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Ava Murphy', 'ava.murphy@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Steven Rogers', 'steven.rogers@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Emma Morgan', 'emma.morgan@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Andrew Peterson', 'andrew.peterson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Charlotte Bell', 'charlotte.bell@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Joshua Cox', 'joshua.cox@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Amelia Boyd', 'amelia.boyd@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Jose Powell', 'jose.powell@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Harper Long', 'harper.long@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Juan Patterson', 'juan.patterson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Evelyn Hughes', 'evelyn.hughes@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Antonio Flores', 'antonio.flores@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Ella Wash', 'ella.wash@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Diego Atkinson', 'diego.atkinson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Madison Summers', 'madison.summers@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Luis Payne', 'luis.payne@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Scarlett Miles', 'scarlett.miles@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Carlos Stephens', 'carlos.stephens@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Chloe Wade', 'chloe.wade@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Miguel Walsh', 'miguel.walsh@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Grace Buckley', 'grace.buckley@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Juan Hayworth', 'juan.hayworth@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Natalie Osborne', 'natalie.osborne@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Pedro Shepherd', 'pedro.shepherd@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Harper Mann', 'harper.mann@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Francisco Benson', 'francisco.benson@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Lily Mccarty', 'lily.mccarty@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Rafael Sutton', 'rafael.sutton@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Violet Horton', 'violet.horton@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Salvador Garza', 'salvador.garza@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Rose Padilla', 'rose.padilla@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Hector Valencia', 'hector.valencia@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Iris Mcneil', 'iris.mcneil@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Victor Kerr', 'victor.kerr@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Hazel Mccall', 'hazel.mccall@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Arturo Dunlap', 'arturo.dunlap@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Poppy Woodard', 'poppy.woodard@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Leopoldo Wiley', 'leopoldo.wiley@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Penelope Merritt', 'penelope.merritt@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Lorenzo Brewer', 'lorenzo.brewer@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Sienna Stafford', 'sienna.stafford@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Gonzalo Copley', 'gonzalo.copley@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Lillian Malone', 'lillian.malone@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Sergio Frazier', 'sergio.frazier@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Aurora Mckinney', 'aurora.mckinney@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Raul Donovan', 'raul.donovan@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Naomi Shipley', 'naomi.shipley@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Manuel Mcconnell', 'manuel.mcconnell@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Jasmine Cramer', 'jasmine.cramer@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Enrique Singleton', 'enrique.singleton@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Adelaide Hines', 'adelaide.hines@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Roberto Robins', 'roberto.robins@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Melody Weeks', 'melody.weeks@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Javier Mccarthy', 'javier.mccarthy@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Ivy Barfield', 'ivy.barfield@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Juan Mcdiarmid', 'juan.mcdiarmid@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Paisley Mcneill', 'paisley.mcneill@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Alberto Sanchez', 'alberto.sanchez@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Elena Seymour', 'elena.seymour@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Felipe Sheridan', 'felipe.sheridan@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Clara Shields', 'clara.shields@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Ignacio Shields', 'ignacio.shields@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Nora Shinner', 'nora.shinner@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Jorge Shelly', 'jorge.shelly@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Stella Shields', 'stella.shields@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Mateo Shields', 'mateo.shields@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');
insert into players (name, email, password, role) values ('Ophelia Shields', 'ophelia.shields@gmail.com', '$2a$10$Y50UaEVPoxnzfzEqPcEucOHmSx8p676GZ8WzG9a1.VvGk.C.pYV6W', 'PLAYER');

insert into fighters (name, health, damage, resistance) values ('Kazuya Mishima', 1400, 95.0, 8.5);
insert into fighters (name, health, damage, resistance) values ('Xiaoyu Ling', 1050, 42.5, 3.2);
insert into fighters (name, health, damage, resistance) values ('Marshall Law', 1100, 88.75, 6.0);
insert into fighters (name, health, damage, resistance) values ('King', 1350, 92.0, 7.8);
insert into fighters (name, health, damage, resistance) values ('Nina Williams', 1080, 85.5, 5.5);
insert into fighters (name, health, damage, resistance) values ('Hwoarang', 1120, 84.0, 5.2);
insert into fighters (name, health, damage, resistance) values ('Yoshimitsu', 1090, 76.25, 4.8);
insert into fighters (name, health, damage, resistance) values ('Armor King', 1320, 89.0, 7.2);
insert into fighters (name, health, damage, resistance) values ('Paul Phoenix', 1200, 91.5, 6.8);
insert into fighters (name, health, damage, resistance) values ('Jack-8', 1450, 85.0, 9.0);
insert into fighters (name, health, damage, resistance) values ('Asuka Kazama', 1070, 72.0, 4.5);
insert into fighters (name, health, damage, resistance) values ('Steve Fox', 1110, 79.5, 5.3);
insert into fighters (name, health, damage, resistance) values ('Eddy Gordo', 1130, 81.25, 5.6);
insert into fighters (name, health, damage, resistance) values ('Alisa Bosconovitch', 1095, 75.75, 4.9);
insert into fighters (name, health, damage, resistance) values ('Zafina', 1025, 73.5, 4.1);
insert into fighters (name, health, damage, resistance) values ('Lili', 1080, 68.0, 3.8);
insert into fighters (name, health, damage, resistance) values ('Forest Law', 1150, 82.5, 5.8);
insert into fighters (name, health, damage, resistance) values ('Miguel', 1320, 90.25, 7.1);
insert into fighters (name, health, damage, resistance) values ('Sergei Dragunov', 1380, 87.5, 8.2);
insert into fighters (name, health, damage, resistance) values ('Devil Kazuya', 1420, 98.0, 9.2);
insert into fighters (name, health, damage, resistance) values ('Lars Alexandersson', 1200, 80.75, 6.2);
insert into fighters (name, health, damage, resistance) values ('Leo Kliesen', 1160, 83.5, 5.9);
insert into fighters (name, health, damage, resistance) values ('Marduk', 1440, 86.0, 8.8);
insert into fighters (name, health, damage, resistance) values ('Bob', 1460, 78.5, 9.1);
insert into fighters (name, health, damage, resistance) values ('Raven', 1105, 77.25, 5.4);
insert into fighters (name, health, damage, resistance) values ('Kunimitsu II', 1095, 81.0, 5.1);
insert into fighters (name, health, damage, resistance) values ('Lucky Chloe', 1035, 65.5, 3.5);
insert into fighters (name, health, damage, resistance) values ('Claudio Seraphim', 1125, 79.75, 5.5);
insert into fighters (name, health, damage, resistance) values ('Josie Rizal', 1110, 70.25, 4.7);
insert into fighters (name, health, damage, resistance) values ('Katarina Alves', 1140, 75.5, 5.0);
insert into fighters (name, health, damage, resistance) values ('Gigas', 1480, 80.0, 9.3);
insert into fighters (name, health, damage, resistance) values ('Shaheen', 1220, 84.75, 6.5);
insert into fighters (name, health, damage, resistance) values ('Akuma', 1250, 96.5, 7.3);
insert into fighters (name, health, damage, resistance) values ('Ganryu', 1300, 82.0, 7.5);
