insert into fighters (name, health, damage, resistance) values ('Kazuya Mishima', 1400, 95.0, 8.5);
insert into fighters (name, health, damage, resistance) values ('Xiaoyu Ling', 1050, 42.5, 3.2);
insert into fighters (name, health, damage, resistance) values ('Marshall Law', 1100, 88.75, 6.0);
insert into fighters (name, health, damage, resistance) values ('King', 1350, 92.0, 7.8);
insert into fighters (name, health, damage, resistance) values ('Nina Williams', 1080, 85.5, 5.5);
insert into fighters (name, health, damage, resistance) values ('Hwoarang', 1120, 84.0, 5.2);
insert into fighters (name, health, damage, resistance) values ('Yoshimitsu', 1090, 76.25, 4.8);
insert into fighters (name, health, damage, resistance) values ('Armor King', 1320, 89.0, 7.2);
insert into fighters (name, health, damage, resistance) values ('Paul Phoenix', 1200, 91.5, 6.8);
insert into fighters (name, health, damage, resistance) values ('Jack-8', 1450, 85.0, 9.0);
insert into fighters (name, health, damage, resistance) values ('Asuka Kazama', 1070, 72.0, 4.5);
insert into fighters (name, health, damage, resistance) values ('Steve Fox', 1110, 79.5, 5.3);
insert into fighters (name, health, damage, resistance) values ('Eddy Gordo', 1130, 81.25, 5.6);
insert into fighters (name, health, damage, resistance) values ('Alisa Bosconovitch', 1095, 75.75, 4.9);
insert into fighters (name, health, damage, resistance) values ('Zafina', 1025, 73.5, 4.1);
insert into fighters (name, health, damage, resistance) values ('Lili', 1080, 68.0, 3.8);
insert into fighters (name, health, damage, resistance) values ('Forest Law', 1150, 82.5, 5.8);
insert into fighters (name, health, damage, resistance) values ('Miguel', 1320, 90.25, 7.1);
insert into fighters (name, health, damage, resistance) values ('Sergei Dragunov', 1380, 87.5, 8.2);
insert into fighters (name, health, damage, resistance) values ('Devil Kazuya', 1420, 98.0, 9.2);
insert into fighters (name, health, damage, resistance) values ('Lars Alexandersson', 1200, 80.75, 6.2);
insert into fighters (name, health, damage, resistance) values ('Leo Kliesen', 1160, 83.5, 5.9);
insert into fighters (name, health, damage, resistance) values ('Marduk', 1440, 86.0, 8.8);
insert into fighters (name, health, damage, resistance) values ('Bob', 1460, 78.5, 9.1);
insert into fighters (name, health, damage, resistance) values ('Raven', 1105, 77.25, 5.4);
insert into fighters (name, health, damage, resistance) values ('Kunimitsu II', 1095, 81.0, 5.1);
insert into fighters (name, health, damage, resistance) values ('Lucky Chloe', 1035, 65.5, 3.5);
insert into fighters (name, health, damage, resistance) values ('Claudio Seraphim', 1125, 79.75, 5.5);
insert into fighters (name, health, damage, resistance) values ('Josie Rizal', 1110, 70.25, 4.7);
insert into fighters (name, health, damage, resistance) values ('Katarina Alves', 1140, 75.5, 5.0);
insert into fighters (name, health, damage, resistance) values ('Gigas', 1480, 80.0, 9.3);
insert into fighters (name, health, damage, resistance) values ('Shaheen', 1220, 84.75, 6.5);
insert into fighters (name, health, damage, resistance) values ('Akuma', 1250, 96.5, 7.3);
insert into fighters (name, health, damage, resistance) values ('Ganryu', 1300, 82.0, 7.5);
